language: objective-c
osx_image: xcode10.1
dist: trusty

cache:
  directories:
  - vendor/bundle

before_script:
- bundle exec danger
script:
- fastlane coverage

branches:
  only:
  - master

notifications:
  slack:
    secure: vO6jZSJAZT7Qgp2EiA0iBWhhz5PWymCJ9pw4WGVoTmTRFEZLrBZm4chMGJbe4dToPUQLTrmVSAKkCqlwKxrH3XdPq07HatBuUxW3wG7tyOE9xhmISgQ+cEbIJpzqEM8Hz2vxk4+W0jLmWT+O2Gte1fcpfVASwci+GDhDWbCky8w1H/mpfN0f9lcSAZW7hJVFhWJbmQuEhpNv0vWTNuNFQC5D7TQYViAj5pKI6GxwLZLUihrBjegvT0Gr6X8bApUfIcdBhcJhYnZeQf4keRaoqlgLBlzUW5GtUO519iByn5F+SiRdt5Q4XQtO7una2+blDQYADYS8cdW23COcajLrazBtyDmitOqfLcp7DoPAktwL3C4XfIOjG1bcKZkOSSp/PV8IeyiGFXJhVa4g3k50w9GJ9Aydth0cxnmL20/d+vbiO1EjlrGHfmoR857NHwH2ME1uXTtepzYNDdGJS126P1U5jXgolYcarOyZ+JJCBS/PubJ39yESfzu8mz/R4Nd0D5dQAdUmILYAqfJSKUT6IMLEoXr4VUGzsCRgY3CMsco8zwGw9ICIjjjASmdgB6ra4yvbSzu6BMWzog2lJ2rdjZcZ7ktLhxP8zfJMhRH36ZvTfZSXeKDKTUHl3d4FdWQTb4CWZLMYjVmdCXJLjqnEw5av/Cxz8+S/tXfMMbhgCro=
