language: objective-c
osx_image: xcode10.1
dist: trusty

cache:
  directories:
  - vendor/bundle

addons:
  sonarcloud:
    organization: scior-github
    token:
      secure: "0CLSN1u8T0q+2CKTi2QzFJTsA8Dzr6rV1qcC5JRRm0IajWWM36EpDDOqIDFRE8v0o71CA6VcWWc6dS2Erd8C/Fan0K97cCHmiUXyhhX/s4xLf5niETrywrMGywkd1TelF4a355kLBdWQ69GuOe5xBP842gxtYkCE7Fq9XiT29mW3P5lG+FLa/fqBRBe5Ph9yDTHiqnBLtsOnhEHNsUEp8pK6dzSFBohARZshVOPectYcUcn5aia8q9lu5XlNOer4x/N9aFfuGB3Y9RzD5iOaBpEhExZpS0nfw258GR+pmM0E597RrVegjmDvc45LAXcVkW2cMNj+9qz4Zggq3WtqrPihCo+lfRqTXB1kBBxGLl9ADCZfkL9pZ2OlUr/NgO8eIqeRqXuhS0CDuaNqHRRIOT3P1F1YKLCAcji8JYw8wRbMC0mhQO36T7qrZxytEXxMF4usCamDQe9d1CUwW1waXqf2Xi8sKuxqF34b8pIbPHcLpf94nz9Wt/hMaIEv68LJCflgoOIJbRxIIAsPcuthYjsCnnoWg1sq/LaNIbWpbz4M3X7a6r+bHXAeiZHuTJXc3flTLCS4jBtgr3lVKjbK9MlEn2BfxU3oxhnvvx0u/oDJwkB13tCAV5JfL8ot0/6ujRzrXRsLQwLnNhZowmIPMPppSofWIMPLHYTWHAxToBc="

before_script:
  - bundle exec danger

script:
  - fastlane coverage
  - find . -type d | grep -E  ".xccovarchive$" | xargs -I@ bash utils/xccov-to-sonarqube-generic.sh @ > sonarqube-generic-coverage.xml 
  - sonar-scanner -X

branches:
  only:
  - master

notifications:
  slack:
    secure: vD4u2dU/iV8AD4ydOETi5SJ1ihvRf3LRtEgro1smh56X19x6wrL8Lt96Ky44yosrDM3tNCVUq2ZbICr6WpdkvdnquRS8HCkku3xTEXq9vCnn94kVZ4eT91ZkzvHbLKdGH+Lak/t4E6A9MpmzTMzM9VmiauAXh5bS7E2nvxgg+8belCELs2KNdecPUiooty/baVRDqhFJc83NdU5Q7Gj2+7PTSBCy2uSmwRjbUf9Kl0Hr+kRy/HR3bLsiljkkWbqfe95y1xSHfKbVfDIqRyqpRU6BjKbVJlmCuWasOLg0mksxwtnYxGa3DI4QozhoRadIN3gbtSuzAb/zfz5/duOaBbnR9YKYnCP4Okj35uPEipxCRuIAuIBH2teSW1fcHSWMxemL+QxwV87l0l1fJn7EMPeMKuFrBmcFvXt4Etjfg9hpKt7PXqF3TscxF90YrsLBr4utxMuV3mEXS0o616NoQ9FVXOTpFOLlOCcXm1qoTK1mWHv4wiZJF63CffNe5PEuIiK9l9tNEPCz1bJtzp+m9sfFlWotupUALQGBJtIgALgHEy+2V7F7RWX56UnMcU+tVKER28AXbOhATzo0O2wUCZIJU5PPAqyQdYMlnuY7rnwnkUYXHo538Q0gkk/ELkW2/UnT0Yf/cZYT4Gs/yZTzzqZxRUwViq6PswmmGgCFa/s=
